#!/bin/sh

pidFile="/tmp/aesdDaemon.pid"

case $1 in
    stop)
        kill $(cat $pidFile)
        rm $pidFile
    ;;
    start)
        aesdsocket -d
        sleep 1
        PID=$(pgrep aesdsocket)
        echo $PID > $pidFile
    ;;
    *)
        exit -1
    ;;
esac
