#!/bin/sh

pidFile="/tmp/aesdDaemon.pid"

case $1 in
    stop)
        kill $(cat $pidFile)
        rm $pidFile
    ;;
    start)
        /usr/bin/aesdsocket -d
        sleep 1
        PID=$(pidof aesdsocket)
        echo $PID > $pidFile
    ;;
    *)
        exit -1
    ;;
esac
